# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zySkrjKAXsiF17E50C_KxGZlTMUr1Qct
"""

from datetime import datetime
import pandas as pd
import numpy as np

# load the data
df = pd.read_csv("COVID19 - COVID19.csv")
display(df.shape, df.info())

# check for missing values
df.isnull().sum()

df["Result"].value_counts()

#df["Result"]
dfn = df[(df["Result"] == "PENDING") | (df["Result"] == "NEGATIVE") |\
     (df["Result"] == "POSITIVE") | (df["Result"] == "INDETERMINATE")]
dfn.shape

# check for missing values
dfn.info()

# drop columns were missing values is above 50% of its entire data in the column
dfn = dfn.drop(["Chills or sweats", "Confused or disoriented", "Difficulty breathing or Dyspnea",\
    "Digested blood or coffee grounds in vomit", "Pain behind eyes or Sensitivity to light",\
    "Bleeding from the eyes", "Fluid in the lung cavity", "Fluid in lung cavity in auscultation",\
    "Fluid in cavity through X-Ray", "Bleeding of the gums", "Joint pain or arthritis",\
    "Malaise", "Muscle pain", "Other clinical symptoms", "Pharyngeal exudate", "Rapid breathing",\
    "Maculopapular rash", "Bleeding or bruising", "Abnormal lung X-Ray findings", "Conjunctivitis",\
    "Acute respiratory distress syndrome", "Pneumonia (clinical or radiologic)", "Cough with sputum",\
    "Cough with heamoptysis", "Enlarged lymph nodes", "Wheezing", "Skin ulcers", "Inability to walk",\
    "Indrawing of chest wall", "Other complications", "Specify other complications", ], axis = 1)

display(dfn.shape, dfn.head(3))

dfn.info()

# drop rows with missing date of birth
dfn = dfn.dropna(subset=["Birth Year"])

# evaluate the age from year of birth
# Convert to integer (if needed)
dfn['Birth Year'] = dfn['Birth Year'].astype(int)

# Get the current year
current_year = datetime.now().year

# Compute the age
dfn['age'] = current_year - dfn['Birth Year']

dfn.head(2)

"""### replace missing values"""

# Columns where "UNKNOWN" should be replaced with NaN
columns_to_replace_unknown = ["Chest pain", "Cough", 'Diarrhea','Fatigue or general weakness', 'Fever', 'Headache',
                    'Thorax (sore throat)', 'Nausea', 'Runny nose','Sore throat or pharyngitis', 'Vomiting',
                    'Loss of Taste', 'Loss of Smell']  # Only replace in these columns

# Replace "UNKNOWN" with NaN in selected columns only
dfn[columns_to_replace_unknown] = dfn[columns_to_replace_unknown].replace("UNKNOWN", pd.NA)

# Columns to fill missing values for
columns_to_fill = ["Chest pain", "Cough", 'Diarrhea','Fatigue or general weakness', 'Fever', 'Headache',
                    'Thorax (sore throat)', 'Nausea', 'Runny nose','Sore throat or pharyngitis', 'Vomiting',
                    'Loss of Taste', 'Loss of Smell']

# Define conditions
conditions = {
    "child_male": (dfn['Sex'] == 'MALE') & (dfn['age'] < 18),
    "child_female": (dfn['Sex'] == 'FEMALE') & (dfn['age'] < 18),
    "adult_male": (dfn['Sex'] == 'MALE') & (dfn['age'] > 18) & (dfn['age'] < 50),
    "adult_female": (dfn['Sex'] == 'FEMALE') & (dfn['age'] > 18) & (dfn['age'] < 50),
    "old_male": (dfn['Sex'] == 'MALE') & (dfn['age'] > 50),
    "old_female": (dfn['Sex'] == 'FEMALE') & (dfn['age'] > 50),
}

# Fill missing values for each column based on the mode of each condition
for col in columns_to_fill:
    for condition_name, condition in conditions.items():
        subset = dfn.loc[condition, col].dropna()  # Get non-null values for this condition
        if not subset.empty:
            mode_value = subset.mode().iloc[0]  # Get mode (most frequent value)
            dfn.loc[condition & dfn[col].isna(), col] = mode_value  # Fill NaNs only

dfn.info()

#
dfn["Sex"].value_counts()

#
dfn = dfn[(dfn["Sex"] != "UNKNOWN") | (dfn["Sex"] != "OTHER")]
dfn.info()

dfn["Sore throat or pharyngitis"].value_counts(dropna=False)

# drop missing values that are less than 5% of the population in a column
dfm = dfn.dropna()
dfm.info()

# check for duplicate entries
dfm.duplicated().sum()

# 61010 - 58519
dfm = dfm.drop_duplicates(keep="first")
dfm.shape

dfm["Result"].value_counts()

# save the cleaned data
dfm = dfm[dfm["Result"] != "PENDING"]
dfm.to_csv("cleaned_covid.csv", index=False)

